language: objective-c

env:
  - APM_TEST_PACKAGES=build

before_script:
  - npm install
  - npm test

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10
